# NumPy array

It’s a combination of a memory address, a data type, a shape and strides

In [2]:
import numpy as np

In [7]:
my_np_arr = np.random.randint(0,10,9).reshape(3,3)
print(my_np_arr)

[[9 8 9]
 [2 2 3]
 [7 9 7]]


- print memory address
- print shape
- print data type
- print stride

In [8]:
print(my_np_arr.data)
print(my_np_arr.shape)
print(my_np_arr.dtype)
print(my_np_arr.strides)

(3, 3)
int32
(12, 4)


### Create a full array

In [12]:
full_array = np.full((3,4),8)
print(full_array)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


### Save and load NumPy arrays to file

In [14]:
np.savetxt('full.txt', full_array, delimiter=',')

In [15]:
arr_from_txt = np.loadtxt('full.txt', delimiter=',')

In [16]:
print(arr_from_txt)

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]


- Print the number of dimensions
- Print the number of elements
- Print information about memory layout
- Print the length of one array element in bytes
- Print the total consumed bytes

In [17]:
print(my_np_arr.ndim)
print(my_np_arr.size)
print(my_np_arr.flags)
print(my_np_arr.itemsize)
print(my_np_arr.nbytes)

2
9
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
4
36


### Change the data type

In [18]:
my_np_arr.astype(float)

array([[9., 8., 9.],
       [2., 2., 3.],
       [7., 9., 7.]])

In [19]:
print(np.transpose(my_np_arr))

[[9 2 7]
 [8 2 9]
 [9 3 7]]


In [20]:
np.resize(my_np_arr, (5,6))

array([[9, 8, 9, 2, 2, 3],
       [7, 9, 7, 9, 8, 9],
       [2, 2, 3, 7, 9, 7],
       [9, 8, 9, 2, 2, 3],
       [7, 9, 7, 9, 8, 9]])

### Flatten

In [21]:
my_np_arr.ravel()

array([9, 8, 9, 2, 2, 3, 7, 9, 7])

### Stack arrays

In [25]:
print(np.vstack((my_np_arr, np.resize(arr_from_txt, (3,3)))))

[[9. 8. 9.]
 [2. 2. 3.]
 [7. 9. 7.]
 [8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [27]:
print(np.r_[my_np_arr, np.resize(arr_from_txt, (3,3))])

[[9. 8. 9.]
 [2. 2. 3.]
 [7. 9. 7.]
 [8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


### Matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method

In [28]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

In [29]:
A * B

array([[2, 0],
       [0, 4]])

In [30]:
A @ B

array([[5, 4],
       [3, 4]])

In [31]:
A.dot(B)

array([[5, 4],
       [3, 4]])

### Create array from function

In [32]:
def f(x,y):
    return 3*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]
 [12 13 14 15]]


### Iterating


In [33]:
for element in b.flat:
    print(element)

0
1
2
3
3
4
5
6
6
7
8
9
9
10
11
12
12
13
14
15
