# NumPy Subseting

In [37]:
import numpy as np

In [38]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[8]

8

In [40]:
arr[2:6]

array([2, 3, 4, 5])

In [41]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Broadcasting

In [43]:
arr[0:5] = 20
print(arr)
arr = np.arange(0, 11)

[20 20 20 20 20  5  6  7  8  9 10]


In [44]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Copying

In [47]:
arr_copy = arr.copy()

In [48]:
arr_copy[:] = 55
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]


## 2D array

In [49]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [50]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
arr_2d[1][2]

30

In [52]:
arr_2d[0]

array([ 5, 10, 15])

In [53]:
arr_2d[2,1]

40

In [54]:
arr_2d[1,:]

array([20, 25, 30])

In [55]:
arr_2d[:,2]

array([15, 30, 45])

In [56]:
arr_2d[1:3,0:2]

array([[20, 25],
       [35, 40]])

## Conditional subseting

In [57]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [60]:
fibIndices = np.array([1, 1, 2, 3])

In [62]:
randomRow = np.random.random((10,1))
print(randomRow)

[[0.66611299]
 [0.22268222]
 [0.27716814]
 [0.34086308]
 [0.72659084]
 [0.2431716 ]
 [0.22422026]
 [0.0603993 ]
 [0.94774064]
 [0.69253721]]


In [63]:
randomRow[fibIndices]

array([[0.22268222],
       [0.22268222],
       [0.27716814],
       [0.34086308]])

Create a square array

In [65]:
squareArray = np.arange(1,10).reshape((3,3))
print(squareArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Returns average of all elements

In [68]:
sqAverage = np.average(squareArray)
print(sqAverage)

5.0


Returns the standard deviation of all the elements in the given array

In [66]:
sqStdDev = np.std(squareArray)
print(sqStdDev)

2.581988897471611


make a copy of squareArray that will be "clamped". It will only contain values within one standard deviation of the mean. Values that are too low or to high will be set to the min and max respectively. We set dtype=float because sqAverage and sqStdDev are floating point numbers, and we don't want to truncate them down to integers.

In [76]:
clampedSqArray = np.array(squareArray.copy(), dtype=float)
print(clampedSqArray)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [77]:
clampedSqArray[(squareArray-sqAverage) > sqStdDev] = sqAverage+sqStdDev

In [78]:
clampedSqArray[(squareArray-sqAverage) < -sqStdDev] = sqAverage-sqStdDev

In [79]:
print(clampedSqArray)

[[2.4180111 2.4180111 3.       ]
 [4.        5.        6.       ]
 [7.        7.5819889 7.5819889]]
