# NumPy Arrays

### Import numpy

In [1]:
import numpy as np

### Creating numpy array from list

In [2]:
my_list = [1, 2, 3]

In [4]:
np_arr = np.array(my_list)

In [5]:
np_arr

array([1, 2, 3])

### Create 2D numpy array from list

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Create np array from build in function arange - give start, stop and step size

In [10]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

### Create array of 0's

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### Give tuple of dimensions

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Create numpy array of ones

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Populate with evenly spaced numbers in interval - start, stop and number

In [18]:
np.linspace(0, 6, 15)

array([0.        , 0.42857143, 0.85714286, 1.28571429, 1.71428571,
       2.14285714, 2.57142857, 3.        , 3.42857143, 3.85714286,
       4.28571429, 4.71428571, 5.14285714, 5.57142857, 6.        ])

### Create an identity matrix

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Create array of random numbers of uniform distribution

In [21]:
np.random.rand(5)

array([0.38785569, 0.80807836, 0.45260077, 0.69153899, 0.57944002])

### Create 2D array

In [22]:
np.random.rand(4,5)

array([[0.60993038, 0.23480466, 0.03051507, 0.57055754, 0.89395183],
       [0.51604254, 0.56647293, 0.15517636, 0.68539076, 0.83745026],
       [0.95666868, 0.5655251 , 0.57759507, 0.54007635, 0.83497837],
       [0.10428562, 0.4533663 , 0.66099565, 0.1181754 , 0.60878568]])

### Gausian distribution

In [24]:
np.random.randn(4)

array([ 1.96427909,  0.20603611,  1.62531445, -0.44449937])

In [25]:
np.random.randn(4,3)

array([[ 0.29317147,  0.16873174,  0.5235201 ],
       [ 0.23214243, -1.29182947, -0.5710457 ],
       [-0.35987951,  0.85289503,  0.92684058],
       [ 0.9181216 ,  0.70135608, -0.17864904]])

### Generate random int

In [27]:
np.random.randint(1, 100)

30

### Generate 10 random ints from 1 to 100

In [28]:
np.random.randint(1,100,10)

array([63, 46, 36, 83, 73, 32, 98, 55, 64, 55])

## Atributes of np array
create two arrays for manipulation

In [31]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 9, 11,  4, 31, 23, 47, 18, 26, 14, 39])

### Reshape dimensions of array
Total size of the array must be unchanged. 5*5=25 - original size of array

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Max, min values

In [37]:
ranarr.max()

47

In [38]:
ranarr.min()

4

#### Get index of max and min value

In [39]:
ranarr.argmax()

5

In [40]:
ranarr.argmin()

2

### Get shape

In [41]:
arr.shape

(25,)

In [47]:
arr_2d = arr.reshape(5,5)

In [48]:
arr_2d.shape

(5, 5)

### Data type

In [49]:
arr.dtype

dtype('int32')

### Random choice

In [2]:
np.random.choice(['Name1', 'Name2', 'Name3', 'Name4', 'Name5'], 3, replace=True)

array(['Name5', 'Name3', 'Name1'], dtype='<U5')

In [5]:
np.random.choice(['Name1', 'Name2', 'Name3', 'Name4', 'Name5'], 10, replace=True, p=[0.1, 0.2, 0.4, 0.2, 0.1])

array(['Name3', 'Name3', 'Name3', 'Name3', 'Name4', 'Name2', 'Name3',
       'Name1', 'Name3', 'Name3'], dtype='<U5')