# Spliting, copies, type casting

In [1]:
import numpy as np

In [7]:
arr = np.floor(10*np.random.random((2,12)))
arr

array([[7., 9., 7., 6., 0., 4., 2., 6., 8., 8., 9., 9.],
       [4., 1., 7., 3., 6., 9., 9., 7., 6., 1., 7., 8.]])

### Split arr into 3

In [8]:
np.hsplit(arr,3)

[array([[7., 9., 7., 6.],
        [4., 1., 7., 3.]]), array([[0., 4., 2., 6.],
        [6., 9., 9., 7.]]), array([[8., 8., 9., 9.],
        [6., 1., 7., 8.]])]

### Split arr after the third and the fourth column

In [11]:
np.hsplit(arr,(3,4))

[array([[7., 9., 7.],
        [4., 1., 7.]]), array([[6.],
        [3.]]), array([[0., 4., 2., 6., 8., 8., 9., 9.],
        [6., 9., 9., 7., 6., 1., 7., 8.]])]

## Deep Copy

In [15]:
a = np.arange(12)
b = a.copy()

In [16]:
b is a

False

In [17]:
b.base is a

False

### Type casting

In [18]:
a.dtype

dtype('int32')

In [21]:
c = a.astype(np.str_)

In [22]:
c.dtype

dtype('<U11')

### Indexing wiht arrays of indices

In [25]:
a = np.arange(12) ** 2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

array of indices

In [26]:
i = np.array([1,1,4,8,2])

In [27]:
a[i]

array([ 1,  1, 16, 64,  4], dtype=int32)

2d array of indices

In [28]:
j = np.array([[2,4],[2,8]])

In [29]:
a[j]

array([[ 4, 16],
       [ 4, 64]], dtype=int32)

### ix_() function
The ix_ function can be used to combine different vectors so as to obtain the result for each n-uplet. For example, if you want to compute all the a+b*c for all the triplets taken from each of the vectors a, b and c

In [31]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])

In [32]:
ax, bx, cx = np.ix_(a,b,c)

In [33]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [34]:
bx

array([[[8],
        [5],
        [4]]])

In [35]:
cx

array([[[5, 4, 6, 8, 3]]])

In [36]:
print(ax.shape, bx.shape, cx.shape)

(4, 1, 1) (1, 3, 1) (1, 1, 5)


In [37]:
result = ax+bx*cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [38]:
result[3,2,4]

17

In [39]:
a[3]+b[2]+c[4]

12