In [70]:
import numpy as np
import math
np.random.seed(123)

### 1.1 

In [71]:
my_arr = np.random.uniform(-4, 4, 30)
my_arr

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

In [72]:
my_arr[np.logical_and(my_arr >= -2, my_arr <= -1) | np.logical_and(my_arr >= 1, my_arr <=2)]

array([ 1.57175348, -1.71088532,  1.75575176,  1.47863791, -1.25457587,
        1.83239766,  1.90396325,  1.07520767,  1.7956426 ,  1.77954706,
       -1.41632869, -1.10569076, -1.65028763,  1.04780899])

In [73]:
my_arr[my_arr >= 0].size

15

In [74]:
np.mean(np.absolute(my_arr))

1.5260572308400788

In [75]:
np.max(my_arr)

3.846113587076924

In [76]:
np.min(my_arr)

-3.522576827123453

In [77]:
np.min(np.absolute(my_arr))

0.15254478812511252

In [78]:
np.max(np.absolute(my_arr))

3.846113587076924

In [79]:
my_arr[np.argmin(np.absolute(my_arr - 2))]

1.9039632458562856

In [80]:
my_arr[np.argmax(np.absolute(my_arr - 2))]

-3.522576827123453

In [91]:
np.modf(my_arr)

(array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
        -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
        -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
         0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
         0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
        -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899]),
 array([ 1., -1., -2.,  0.,  1., -0.,  3.,  1., -0., -0., -1.,  1., -0.,
        -3., -0.,  1., -2., -2.,  0.,  0.,  1.,  2.,  1.,  0.,  1., -1.,
        -1., -2., -1.,  1.]))

In [82]:
np.interp(my_arr, (my_arr.min(), my_arr.max()), (-1, 1))

array([ 0.38269625, -0.50827314, -0.63700783,  0.06751533,  0.43263682,
       -0.21086968,  1.        ,  0.35742295, -0.08531046, -0.2781575 ,
       -0.38442224,  0.45343994, -0.17728806, -1.        , -0.26528848,
        0.47286418, -0.73332828, -0.74861452,  0.02460209,  0.02520185,
        0.24792446,  0.71483149,  0.44346393,  0.19716386,  0.4390953 ,
       -0.42832498, -0.34401205, -0.63394237, -0.49182579,  0.24048795])

In [83]:
np.mean(my_arr[(my_arr > 3) | (my_arr < -2)] ** 2)

8.315859553206058

In [89]:
string_arr = np.where(my_arr>0, "nieujemna", "ujemna")
string_arr

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna'], dtype='<U9')

In [85]:
def std_deviation(elm_list):
    my_mean = np.mean(elm_list)
    my_sum = sum([(x - my_mean)**2 for x in elm_list])
    return math.sqrt(my_sum/len(elm_list))

In [92]:
print(std_deviation(my_arr)**2)

3.155462650642973


In [88]:
minimum = my_arr[0]
for elem in my_arr:
    if minimum > elem:
        minimum = elem
print(minimum)    

-3.522576827123453


In [90]:
maksimum = my_arr[0]
for elem in my_arr:
    if maksimum < elem:
        maksimum = elem
print(maksimum) 

3.846113587076924


In [96]:
def historize(elm_list, k):
    elm_list[np.logical_and(elm_list >= k, elm_list < k+1)] = k + 0.5
    return elm_list
print(historize(my_arr, 0.3))

[ 1.57175348 -1.71088532 -2.18518837  0.8         1.75575176 -0.61514832
  3.84611359  0.8        -0.15254479 -0.86305985 -1.25457587  1.83239766
 -0.49142204 -3.52257683 -0.81564596  1.90396325 -2.54006616 -2.59638595
  0.25241099  0.2546207   0.8         2.5         1.7956426   0.8
  1.77954706 -1.41632869 -1.10569076 -2.17389415 -1.65028763  0.8       ]


### 1.2

In [97]:
def my_covariance(list1, list2):
    if len(list1) != len(list2):
        print("LLists are not equal!")
        return None
    mean_x = np.mean(list1)
    mean_y = np.mean(list2)
    n = len(list1)
    my_sum = list()
    for x, y in zip(list1, list2):
        my_sum.append((x - mean_x)*(y - mean_y))
    return(sum(my_sum)/n)


In [98]:
def pearsons_correlation(list1, list2):
    p_cov = my_covariance(list1, list2)/(std_deviation(list1)*std_deviation(list2))
    return p_cov

In [102]:
x = np.array(list(range(11)))
y = x[::-1]
print(x,y)

[ 0  1  2  3  4  5  6  7  8  9 10] [10  9  8  7  6  5  4  3  2  1  0]


In [103]:
pearsons_correlation(x,y)

-0.9999999999999998

In [113]:
def from_last_corr(list1, list2):
    if not list1.size == list2.size:
        print("Lists are not equal!")
        return None
    n = list1.size
    top = n*(np.sum(list1*list2)-(np.sum(list1)*np.sum(list2)))
    bot = math.sqrt(n*np.sum(list1**2)-(np.sum(list1)**2)) * math.sqrt(n*np.sum(list2**2)-(np.sum(list2)**2))
    return top/bot

In [114]:
from_last_corr(x,y)

-25.999999999999996

### 1.3

In [131]:
def scale(x, out_range=(0, 1)):
    domain = np.min(x), np.max(x)
    y = (x - (domain[1] + domain[0]) / 2) / (domain[1] - domain[0])
    return y * (out_range[1] - out_range[0]) + (out_range[1] + out_range[0]) / 2

In [138]:
def standarize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean)/std
standarize(x)

array([-1.58113883, -1.26491106, -0.9486833 , -0.63245553, -0.31622777,
        0.        ,  0.31622777,  0.63245553,  0.9486833 ,  1.26491106,
        1.58113883])

In [139]:
int(np.mean(standarize(x)))

0

In [140]:
np.std(standarize(x))

1.0

### 1.4

In [141]:
x @ y

165

In [142]:
np.dot(x,y)

165

### 1.5

In [148]:
def rmse(x, y):
    rmse = np.sqrt(np.sum((y-x)**2)/x.size)
    return rmse

rmse(x, y)

6.324555320336759

### 1.6

In [149]:
def mae(x,y):
    return np.sum(np.abs(y-x))/x.size

In [150]:
mae(x,y)

5.454545454545454

### 1.7

In [151]:
def medae(x,y):
    return np.median(np.abs(y-x))

In [152]:
medae(x,y)

6.0

### 1.8

In [165]:
def hamming_distance(s1, s2):
    """Return the Hamming distance between equal-length sequences"""
    if s1.size != s2.size:
        raise ValueError("Undefined for sequences of unequal length")
    return np.sum(s1 != s2)/s1.size

In [166]:
hamming_distance(x,y)

0.9090909090909091

### 1.9

In [205]:
list_A = np.random.uniform(0,1,8)
list_Y = np.random.choice([0,1] ,8)
def cel(Y, A):
    m = Y.size
    return -(1.0/m) * np.sum(Y*np.log(A) + (1-Y)*np.log(1-A))
list_A

array([0.99535848, 0.35591487, 0.76254781, 0.59317692, 0.6917018 ,
       0.15112745, 0.39887629, 0.2408559 ])

In [206]:
cel(list_Y, list_A)

0.5638717911709776

### 1.10

In [228]:
np_list = np.r_[3:4:5j, 3:10]
def lead(x, n):
    ret = x[n:].copy()
    ret = np.pad(ret, (0,n), 'constant', constant_values=(np.NaN))
    return ret

In [229]:
np_list

array([3.  , 3.25, 3.5 , 3.75, 4.  , 3.  , 4.  , 5.  , 6.  , 7.  , 8.  ,
       9.  ])

In [236]:
print(lead(np_list, 3))

[3.75 4.   3.   4.   5.   6.   7.   8.   9.    nan  nan  nan]


In [231]:
def lag(x, n):
    ret = x[:n].copy()
    ret = np.pad(ret, (n,0), 'constant', constant_values=(np.NaN))
    return ret

In [233]:
print(lag(np_list,5))

[ nan  nan  nan  nan  nan 3.   3.25 3.5  3.75 4.  ]


### 1.11

In [253]:
def cumall(x):
    ret = []
    for idx, val in enumerate(x):
        ret.append(np.all(x[:idx+1]))
    return ret

In [254]:
cumall(np.array([True, True, True, False, True, False, True, True]))

[True, True, True, False, False, False, False, False]

In [258]:
def cumany(x):
    ret = []
    for idx, val in enumerate(x):
        ret.append(np.any(x[:idx+1]))
    return ret

In [259]:
cumany(np.array([False, False, True, False, True, False, True, True]))

[False, False, True, True, True, True, True, True]

### 1.12